### ISSUE TITLE
PHP notice on the settings page

### ISSUE THREAD

**Issue by carolinan** [campuspress/divi-accessibility#28]
When I activate the plugin, I see the following notice on the Accessibility settings page:

`Notice: Undefined index: label_subtext in /var/www/html/wp-content/plugins/accessible-divi/admin/class-divi-accessibility-admin.php on line 483`

**Comment by tech55541** [comment]
I will get it fixed up soon. Thanks for reporting.

**Comment by tech55541** [comment]
This should have been fixed up in the last version, sorry for the delay in updating this.

Thanks for your report. :)
