### ISSUE TITLE
Possibility for translating strings

### ISSUE THREAD

**Issue by jbaekz** [campuspress/divi-accessibility#30]
Hi, 

First of all thank you for a great plugin! 

I'm not sure if this is the right place to ask, but I would like to know if it's possible to make the "Skip to content" and "Search" buttons translatable? 

I tried using Loco Translate but couldn't find the strings. 

Kind regards
Jacob

**Comment by alexstine** [comment]
@vladislavbailovic Could you please offer some feedback here? Maybe it is possible?

**Comment by josephfusco** [comment]
Hey @jbaekz, thanks for the kind words and feedback!

We can definitely do this for the "Skip to content" button as the plugin manages that string. I should have a pull request up for this in a little while.

In regards to the "Search" button text, I believe this is coming from the Divi theme itself. While I agree it would be great to have that translated, I think it would be out of scope for this plugin to manage that translation.

cc @alexstine @vladislavbailovic
