### ISSUE TITLE
Unable to expand mobile hamburger menu with keyboard

### ISSUE THREAD

**Issue by LaserLag** [campuspress/divi-accessibility#32]
Pressing ENTER or SPACEBAR does not expand the hamburger menu. This issue is also referenced here: https://wordpress.org/support/topic/aria-support-for-mobile-menu/

I see that it may work for screen reader software but [OCR](https://www.hhs.gov/ocr/index.html) in their auditing requires the website be fully navigable with keyboard-only users in the web browser without any extra software.

**Comment by LaserLag** [comment]
I was able to make the mobile menu open on ENTER or SPACEBAR by changing
`<span class="mobile_menu_bar mobile_menu_bar_toggle" role="button" aria-expanded="false" tabindex="0"></span>`
to
`<button class="mobile_menu_bar mobile_menu_bar_toggle" role="button" aria-expanded="false" tabindex="0"></button>`

**Comment by alexstine** [comment]
@LaserLag This has been a much reported issue and another developer that works on the plugin has fixed this. Now you should be able to expand and collapse the menu in version 2.0.1.

Thanks.
