### ISSUE TITLE
Fix tabs controls value

### ISSUE THREAD

**Issue by KawanSoares** [campuspress/divi-accessibility#47]
According Lighthouse report, the value "tabList" isn't valid, lowercase "tablist" is expected.
<details>
<summary> Screenshot from Lighthouse Report </summary>

![image](https://user-images.githubusercontent.com/3937749/117191128-9b888280-adb6-11eb-937f-9fc9131d637a.png)

</details>

I fixed it by changing the line below:
aria_suport.js: 9
`$(this).attr('role', 'tabList');` to `$(this).attr('role', 'tablist');`

**Comment by alexstine** [comment]
@TxSadhu You want to fix this up and then release a bug fix?

Thanks.
