### ISSUE TITLE
Enter on Mobile menu

### ISSUE THREAD

**Issue by TTG89** [campuspress/divi-accessibility#48]
When clicking enter on the mobile menu the menu doesn't open. 

Current work around I found was changing the span tag to button with small css adjustments

**Comment by alexstine** [comment]
@TTG89 This should be working in the latest release. Could you please give it a try?

https://github.com/campuspress/divi-accessibility/releases/latest

Thanks.

**Comment by TTG89** [comment]
Thanks for the reply. I did confirm that is the version I am running.

**Comment by TTG89** [comment]
Update: It looks like the issue i'm having is with the hamburger menu on the header style full screen. Sorry for the mistake.

**Comment by alexstine** [comment]
No problem at all. Please re-open if you find another issue.

Thanks.
